fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

shop:
    resource: "@ShopBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

oneup_uploader:
    resource: .
    type: uploader

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google
