services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Eshop\ShopBundle\EventListener\UploadListener:
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_upload, method: onUpload }

    Eshop\ShopBundle\EventListener\LocaleListener:
        tags:
            - { name: kernel.event_subscriber }

    fos_user.doctrine_registry:
        alias: doctrine

    Eshop\ShopBundle\Service\EmailNotifier: ~

    Eshop\ShopBundle\Service\SettingsService: ~

    Eshop\ShopBundle\Service\PagesUtilities: ~

    Eshop\ShopBundle\EventListener\SitemapSubscriber:
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }

    Eshop\UserBundle\Form\Type\RegistrationTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: FOS\UserBundle\Form\Type\RegistrationFormType }

    Eshop\ShopBundle\Twig\RawDescriptionExtension:
        public:       false
        tags:
            - { name: twig.extension }

    Eshop\FixturesBundle\Utils\Slugger: ~

    Eshop\ShopBundle\Service\FileUploader:
        arguments: ['%uploads_directory%']

    Eshop\ShopBundle\EventListener\ImageUploadListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: preRemove }

    Eshop\FixturesBundle\DataFixtures\:
        resource: '../../src/Eshop/FixturesBundle/DataFixtures'
        tags: ['doctrine.fixture.orm']
