services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    AppBundle\EventListener\UploadListener:
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_upload, method: onUpload }

    AppBundle\EventListener\LocaleListener:
        tags:
            - { name: kernel.event_subscriber }

    fos_user.doctrine_registry:
        alias: doctrine

    AppBundle\Service\EmailNotifier: ~

    AppBundle\Service\SettingsService: ~

    AppBundle\Service\PagesUtilities: ~

    AppBundle\EventListener\SitemapSubscriber:
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }

    AppBundle\Form\Type\RegistrationTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: FOS\UserBundle\Form\Type\RegistrationFormType }

    AppBundle\Twig\RawDescriptionExtension:
        public:       false
        tags:
            - { name: twig.extension }

    AppBundle\Utils\Slugger: ~

    AppBundle\Service\FileUploader:
        arguments: ['%uploads_directory%']

    AppBundle\EventListener\ImageUploadListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: preRemove }

    AppBundle\DataFixtures\:
        resource: '../../src/AppBundle/DataFixtures'
        tags: ['doctrine.fixture.orm']
